//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace hStore.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.baosight.com/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service() {
            this.Url = "http://192.168.0.117/Service.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/HelloWorld", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/UpdateUser", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateUser(string pram) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        pram});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateUser(string pram, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateUser", new object[] {
                        pram}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUpdateUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/GetCurrentTime", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetCurrentTime() {
            object[] results = this.Invoke("GetCurrentTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCurrentTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCurrentTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndGetCurrentTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/GetVersionInfo", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetVersionInfo(string filename) {
            object[] results = this.Invoke("GetVersionInfo", new object[] {
                        filename});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVersionInfo(string filename, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVersionInfo", new object[] {
                        filename}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetVersionInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/GetVersionInfo2", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetVersionInfo2(string filename, string versionno) {
            object[] results = this.Invoke("GetVersionInfo2", new object[] {
                        filename,
                        versionno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVersionInfo2(string filename, string versionno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVersionInfo2", new object[] {
                        filename,
                        versionno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetVersionInfo2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/GetVersionInfoNone", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetVersionInfoNone(string filename) {
            object[] results = this.Invoke("GetVersionInfoNone", new object[] {
                        filename});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVersionInfoNone(string filename, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVersionInfoNone", new object[] {
                        filename}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetVersionInfoNone(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/UpdateVersionInfo", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateVersionInfo(string versionno, string filename, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileinfo, string groupname) {
            object[] results = this.Invoke("UpdateVersionInfo", new object[] {
                        versionno,
                        filename,
                        fileinfo,
                        groupname});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateVersionInfo(string versionno, string filename, byte[] fileinfo, string groupname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateVersionInfo", new object[] {
                        versionno,
                        filename,
                        fileinfo,
                        groupname}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateVersionInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/getUserInf", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getUserInf(string yhfz) {
            object[] results = this.Invoke("getUserInf", new object[] {
                        yhfz});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUserInf(string yhfz, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUserInf", new object[] {
                        yhfz}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndgetUserInf(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetImpPlan", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetImpPlan(string pram) {
            object[] results = this.Invoke("Store_GetImpPlan", new object[] {
                        pram});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetImpPlan(string pram, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetImpPlan", new object[] {
                        pram}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetImpPlan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetImpPlanByPage", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetImpPlanByPage(string pram, string beginno, string endno) {
            object[] results = this.Invoke("Store_GetImpPlanByPage", new object[] {
                        pram,
                        beginno,
                        endno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetImpPlanByPage(string pram, string beginno, string endno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetImpPlanByPage", new object[] {
                        pram,
                        beginno,
                        endno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetImpPlanByPage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetImpAccOrder", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetImpAccOrder(string pram) {
            object[] results = this.Invoke("Store_GetImpAccOrder", new object[] {
                        pram});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetImpAccOrder(string pram, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetImpAccOrder", new object[] {
                        pram}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetImpAccOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetImpAccOrderByPage", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetImpAccOrderByPage(string pram, string beginno, string endno) {
            object[] results = this.Invoke("Store_GetImpAccOrderByPage", new object[] {
                        pram,
                        beginno,
                        endno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetImpAccOrderByPage(string pram, string beginno, string endno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetImpAccOrderByPage", new object[] {
                        pram,
                        beginno,
                        endno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetImpAccOrderByPage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetExpPlan", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetExpPlan(string pram) {
            object[] results = this.Invoke("Store_GetExpPlan", new object[] {
                        pram});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetExpPlan(string pram, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetExpPlan", new object[] {
                        pram}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetExpPlan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetExpPlanByPage", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetExpPlanByPage(string pram, string beginno, string endno) {
            object[] results = this.Invoke("Store_GetExpPlanByPage", new object[] {
                        pram,
                        beginno,
                        endno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetExpPlanByPage(string pram, string beginno, string endno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetExpPlanByPage", new object[] {
                        pram,
                        beginno,
                        endno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetExpPlanByPage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetExpAccOrder", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetExpAccOrder(string pram) {
            object[] results = this.Invoke("Store_GetExpAccOrder", new object[] {
                        pram});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetExpAccOrder(string pram, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetExpAccOrder", new object[] {
                        pram}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetExpAccOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.baosight.com/Store_GetExpAccOrderByPage", RequestNamespace="http://www.baosight.com/", ResponseNamespace="http://www.baosight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Store_GetExpAccOrderByPage(string pram, string beginno, string endno) {
            object[] results = this.Invoke("Store_GetExpAccOrderByPage", new object[] {
                        pram,
                        beginno,
                        endno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStore_GetExpAccOrderByPage(string pram, string beginno, string endno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Store_GetExpAccOrderByPage", new object[] {
                        pram,
                        beginno,
                        endno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndStore_GetExpAccOrderByPage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
}
