//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5483
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5483.
// 
namespace hStore.SlabWebservice {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSlabYardSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceSlabYard : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ServiceSlabYard() {
            this.Url = "http://192.168.0.80/SlabYard/ServiceSlabYard.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetColumnData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PileData[] GetColumnData(string ColumnNo) {
            object[] results = this.Invoke("GetColumnData", new object[] {
                        ColumnNo});
            return ((PileData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetColumnData(string ColumnNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetColumnData", new object[] {
                        ColumnNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public PileData[] EndGetColumnData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PileData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlanMaterial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetPlanMaterial(string PlanID) {
            object[] results = this.Invoke("GetPlanMaterial", new object[] {
                        PlanID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPlanMaterial(string PlanID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPlanMaterial", new object[] {
                        PlanID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetPlanMaterial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PileData {
        
        /// <remarks/>
        public string ColumnNo;
        
        /// <remarks/>
        public string RowNo;
        
        /// <remarks/>
        public string PileNO;
        
        /// <remarks/>
        public string LayerNO;
        
        /// <remarks/>
        public string MaterialNO;
        
        /// <remarks/>
        public string POHO;
        
        /// <remarks/>
        public decimal DeterminFlag;
    }
}
